# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

from backwardcompatibilityml.loss.new_error import BCNLLLoss
from backwardcompatibilityml.loss.new_error import BCCrossEntropyLoss
from backwardcompatibilityml.loss.new_error import BCBinaryCrossEntropyLoss
from backwardcompatibilityml.loss.new_error import BCKLDivergenceLoss
from backwardcompatibilityml.loss.strict_imitation import StrictImitationNLLLoss
from backwardcompatibilityml.loss.strict_imitation import StrictImitationCrossEntropyLoss
from backwardcompatibilityml.loss.strict_imitation import StrictImitationBinaryCrossEntropyLoss
from backwardcompatibilityml.loss.strict_imitation import StrictImitationKLDivergenceLoss
